services:

  omejdn:
    image: nginx:1.21.6
    container_name: omejdn
    ports:
      - 80:80
    environment:
      - OMEJDN_DOMAIN=${OMEJDN_DOMAIN}
      - OMEJDN_PATH=${OMEJDN_PATH}
      - UI_PATH=${UI_PATH}
    volumes:
      - ./DAPS/nginx.conf:/etc/nginx/templates/default.conf.template

  omejdn-server:
    image: ghcr.io/fraunhofer-aisec/omejdn-server:${OMEJDN_VERSION}
    container_name: omejdn-server
    environment:
      - OMEJDN_ISSUER=${OMEJDN_ISSUER}
      - OMEJDN_FRONT_URL=${OMEJDN_ISSUER}
      - OMEJDN_OPENID=true
      - OMEJDN_ENVIRONMENT=${OMEJDN_ENVIRONMENT}
      - OMEJDN_ACCEPT_AUDIENCE=idsc:IDS_CONNECTORS_ALL
      - OMEJDN_DEFAULT_AUDIENCE=idsc:IDS_CONNECTORS_ALL
      - OMEJDN_ADMIN=${ADMIN_USERNAME}:${ADMIN_PASSWORD}
    volumes:
      - ./DAPS/config:/opt/config
      - ./DAPS/keys:/opt/keys

  omejdn-ui:
    image: ghcr.io/fraunhofer-aisec/omejdn-ui:${UI_VERSION}
    container_name: omejdn-ui
    environment:
      - OIDC_ISSUER=${OMEJDN_ISSUER}
      - API_URL=${OMEJDN_ISSUER}/api/v1
      - CLIENT_ID=adminUI

  connectora:
    image: ghcr.io/international-data-spaces-association/dataspace-connector:7.1.0
    container_name: connectora
    ports:
      - 8080:8080
    volumes:
      - ./DataspaceConnectorA/conf/config.json:/config/config.json
      - ./DataspaceConnectorA/conf/testbed1.p12:/conf/testbed1.p12
      - ./DataspaceConnectorA/conf/connectorA.p12:/config/connectorA.p12
      - ./DataspaceConnectorA/conf/truststore.p12:/config/truststore.p12
    environment:
      - CONFIGURATION_PATH=/config/config.json
      - DAPS_URL=http://omejdn
      - DAPS_TOKEN_URL=http://omejdn/auth/token
      - DAPS_KEY_URL=http://omejdn/auth/jwks.json
      - DAPS_INCOMING_DAT_DEFAULT_WELLKNOWN=/jwks.json
      - SERVER_SSL_KEY-STORE=file:///config/connectorA.p12
      - CLEARING_HOUSE_URL=https://consumer-core:9999

  connectorb:
    image: ghcr.io/international-data-spaces-association/dataspace-connector:7.1.0
    container_name: connectorb
    ports:
      - 8081:8081
    volumes:
      - ./DataspaceConnectorB/conf/config.json:/config/config.json
      - ./DataspaceConnectorB/conf/testbed2.p12:/conf/testbed2.p12
      - ./DataspaceConnectorB/conf/connectorB.p12:/config/connectorB.p12
      - ./DataspaceConnectorB/conf/truststore.p12:/config/truststore.p12
    environment:
      - CONFIGURATION_PATH=/config/config.json
      - SERVER_PORT=8081
      - DAPS_URL=http://omejdn
      - DAPS_TOKEN_URL=http://omejdn/auth/token
      - DAPS_KEY_URL=http://omejdn/auth/jwks.json
      - DAPS_INCOMING_DAT_DEFAULT_WELLKNOWN=/jwks.json
      - SERVER_SSL_KEY-STORE=file:///config/connectorB.p12
      - CLEARING_HOUSE_URL=https://consumer-core:9999

  broker-reverseproxy:
    image: registry.gitlab.cc-asp.fraunhofer.de/eis-ids/broker-open/reverseproxy
    container_name: broker-reverseproxy
    volumes:
      - ./MetadataBroker/server.crt:/etc/cert/server.crt
      - ./MetadataBroker/server.key:/etc/cert/server.key
    ports:
      - "443:443" # IDS-HTTP API
      - "81:80"

  broker-core:
    image: broker-core-testbed:4.2.8
    container_name: broker-core
    build:
      context: ./MetadataBroker/build
    environment:
      - SPARQL_ENDPOINT=http://broker-fuseki:3030/connectorData
      - ELASTICSEARCH_HOSTNAME=broker-elasticsearch
      - SHACL_VALIDATION=true
      - DAPS_VALIDATE_INCOMING=true
      - COMPONENT_URI=https://localhost/
      - COMPONENT_CATALOGURI=https://localhost/connectors/
      - DAPS_URL=http://omejdn/auth/token
    expose:
      - "8080"

  broker-fuseki:
    image: registry.gitlab.cc-asp.fraunhofer.de/eis-ids/broker-open/fuseki
    container_name: broker-fuseki
    volumes:
      - broker-fuseki:/fuseki
    expose:
      - "3030"
      
  logging-service-mongo:
    image: mongo:latest
    container_name: "logging-service-mongo"
    environment:
      MONGO_INITDB_DATABASE: process
    ports:
      - 27019:27017
      
  logging-service:
    build:
      context: .
      dockerfile: .\docker\logging-service-multistage.Dockerfile
    container_name: "logging-service"
    depends_on:
        - document-api
        - keyring-api
        - logging-service-mongo
    environment:
        # Allowed levels: Off, Error, Warn, Info, Debug, Trace
        - API_LOG_LEVEL=Debug
        - RUST_BACKTRACE=1
    ports:
        - "8000:8000"
    volumes:
        - ./clearing-house-app/logging-service/Rocket.toml:/server/Rocket.toml
        - ./clearing-house-app/logging-service/keys:/server/keys
        - ./clearing-house-app/certs:/server/certs
  consumer-core:
    container_name: "consumer-core"
    image: fraunhoferaisec/trusted-connector-core:6.3.0
    tty: true
    stdin_open: true
    volumes:
        - ./trusted-connector/allow-all-flows.pl:/root/deploy/allow-all-flows.pl
        - ./trusted-connector/consumer-keystore.p12:/root/etc/keystore.p12
        - ./trusted-connector/truststore.p12:/root/etc/truststore.p12
        - ./trusted-connector/clearing-house-processors-0.8.0.jar:/root/jars/clearing-house-processors.jar
        - ./trusted-connector/routes/clearing-house-routes.xml:/root/deploy/clearing-house-routes.xml
        - //var/run/docker.sock://var/run/docker.sock
    environment:
      TC_CH_ISSUER_CONNECTOR: "https://w3id.org/idsa/core/issuerConnector"
      TC_CH_AGENT: "https://w3id.org/idsa/core/Agent"
      TC_DAPS_URL: "http://omejdn"
    ports:
        - "8443:8443"
        - "9999:9999"
  document-mongo:
    image: mongo:latest
    container_name: "document-mongo"
    environment:
      MONGO_INITDB_DATABASE: document
    ports:
      - 27017:27017
  keyring-mongo:
    image: mongo:latest
    container_name: "keyring-mongo"
    environment:
      MONGO_INITDB_DATABASE: keyring
    ports:
      - 27018:27017
  document-api:
    build:
      context: .
      dockerfile: .\docker\document-api-multistage.Dockerfile
    container_name: "document-api"
    depends_on:
        - keyring-api
        - document-mongo
    environment:
        # Allowed levels: Off, Error, Warn, Info, Debug, Trace
        - API_LOG_LEVEL=Debug
    ports:
        - "8001:8001"
    volumes:
        - ./clearing-house-app/document-api/Rocket.toml:/server/Rocket.toml
        - ./clearing-house-app/certs:/server/certs
  keyring-api:
    build:
      context: .
      dockerfile: .\docker\keyring-api-multistage.Dockerfile
    container_name: "keyring-api"
    depends_on:
        - keyring-mongo
    environment:
        # Allowed levels: Off, Error, Warn, Info, Debug, Trace
        - API_LOG_LEVEL=Debug
    ports:
        - "8002:8002"
    volumes:
        - ./clearing-house-app/keyring-api/init_db:/server/init_db
        - ./clearing-house-app/keyring-api/Rocket.toml:/server/Rocket.toml
        - ./clearing-house-app/certs:/server/certs
        
volumes:
  broker-fuseki:

networks:
  default:
    external: 
      name: broker-localhost_default
